---
- hosts: ws
  become: yes
  gather_facts: false
  ignore_errors: true
  tasks:
     - name: Modify config file
       lineinfile:
          path: /etc/selinux/semanage.conf
          #regexp: '^module-store ='
          insertafter: '^module-store ='
          line: module-store = serge
          state: absent 
          #create: yes
# We can make our day the best day ever. It is a beleive systemstate.
# This is a test to confirm the transfer to the ansible server.
# Let's do it one more time
